import { useEffect, useState, type FormEvent } from "react";
import logo from "./img/neuroflux_logo_transparente.png";
import "./css/app.css";

const apiUrl = import.meta.env.VITE_API_URL ?? "http://localhost:3333";
type Role = "MASTER" | "ADMIN" | "STUDENT";
type User = { name: string; role: Role };
type Material = { id: number; title: string; description: string; subject: string; grade: number | null; fileUrl: string | null; author: { name: string } };
const token = () => localStorage.getItem("neuroflux_token");
const getUser = (): User | null => { try { return JSON.parse(localStorage.getItem("neuroflux_user") ?? "null") as User | null; } catch { return null; } };
const canManage = (user: User | null) => user?.role === "ADMIN" || user?.role === "MASTER";

export default function App() {
  const [user, setUser] = useState<User | null>(getUser); const [loginOpen, setLoginOpen] = useState(false); const [apiError, setApiError] = useState(false);
  const path = window.location.pathname;
  useEffect(() => { fetch(`${apiUrl}/api/health`).then(r => !r.ok && setApiError(true)).catch(() => setApiError(true)); }, []);
  return <div className="app"><Header user={user} openLogin={() => setLoginOpen(true)} logout={() => { localStorage.clear(); setUser(null); }} />{path === "/materiais" ? <Library /> : path === "/painel" ? <Dashboard user={user} openLogin={() => setLoginOpen(true)} /> : path === "/cadastro" ? <StudentRegistration /> : <Home />}<Footer />{loginOpen && <Login onClose={() => setLoginOpen(false)} onLogin={setUser} />}{apiError && <ApiError />}</div>;
}

function Header({ user, openLogin, logout }: { user: User | null; openLogin: () => void; logout: () => void }) { return <header className="navbar"><nav><a className="brand" href="/"><img src={logo} alt="Neuroflux" /></a><div className="nav-links"><a href="/#series">Séries</a><a href="/materiais">Materiais</a>{canManage(user) && <a href="/painel">Painel</a>}</div>{user ? <div className="session-actions"><span>Olá, {user.name.split(" ")[0]}</span><button className="sign-out" onClick={logout}>Sair</button></div> : <div className="guest-actions"><a href="/cadastro">Criar conta</a><button className="nav-cta" onClick={openLogin}>Entrar</button></div>}</nav></header>; }
function Footer() { return <footer><div className="footer-content"><a className="footer-brand" href="/"><img src={logo} alt="Neuroflux" /></a><p>© 2026 Neuroflux · Reforço de estudos</p><a href="/materiais">Arquivos de estudo</a></div></footer>; }
function Home() { return <main><section className="hero"><div className="hero-copy"><p className="eyebrow">REFORÇO DE ESTUDOS</p><h1>Estudo claro, no seu ritmo.</h1><p className="intro">Escolha sua série, abra um material e comece a estudar.</p><div className="hero-actions"><a className="button button-primary" href="/materiais">Ver arquivos de estudo</a><a className="text-link" href="#series">Escolher minha série →</a></div></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1529390079861-591de354faf5?auto=format&fit=crop&w=1000&q=85" alt="Estudante revisando materiais" /><aside className="study-note"><p className="eyebrow">COMECE POR AQUI</p><h2>Escolha um material e comece.</h2><ul><li>Guias por assunto</li><li>Listas para praticar</li><li>Conteúdos por série</li></ul></aside></div></section><section className="series-section" id="series"><div className="section-heading"><p className="eyebrow">POR SÉRIE</p><h2>Encontre seu ponto de partida.</h2></div><div className="series-grid"><Series n="01" title="1º ano" text="Bases para acompanhar as disciplinas." /><Series n="02" title="2º ano" text="Revisão dos conteúdos centrais." /><Series n="03" title="3º ano" text="Preparação para provas e vestibulares." /></div></section></main>; }
function Series({ n, title, text }: { n: string; title: string; text: string }) { return <article className="series-card"><span>{n}</span><h3>{title}</h3><p>{text}</p><a href="/materiais">Ver materiais →</a></article>; }

function Library() {
  const [items, setItems] = useState<Material[]>([]); const [status, setStatus] = useState("Carregando atividades…"); const [filter, setFilter] = useState("Todos");
  useEffect(() => { fetch(`${apiUrl}/api/materials`, { headers: token() ? { Authorization: `Bearer ${token()}` } : {} }).then(async r => { if (r.status === 401) throw new Error("Entre com sua conta para acessar os materiais publicados."); if (!r.ok) throw new Error("Não foi possível carregar a biblioteca agora."); return r.json() as Promise<Material[]>; }).then(data => { setItems(data); setStatus(""); }).catch((e: Error) => setStatus(e.message)); }, []);
  const subjects = ["Todos", ...new Set(items.map(i => i.subject))]; const visible = filter === "Todos" ? items : items.filter(i => i.subject === filter);
  return <main className="library-page"><section className="library-hero library-hero-strong"><p className="eyebrow">BIBLIOTECA DE ESTUDOS</p><h1>Encontre a atividade certa para hoje.</h1><p>Materiais publicados por professores, organizados por disciplina para abrir, praticar e avançar.</p><div className="library-stats"><span><strong>{items.length}</strong> atividades disponíveis</span><span><strong>{subjects.length - 1}</strong> disciplinas</span></div></section><section className="library-content">{!status && <div className="subject-filter">{subjects.map(s => <button key={s} className={filter === s ? "active" : ""} onClick={() => setFilter(s)}>{s}</button>)}</div>}{status ? <p className="library-status">{status}</p> : <div className="material-grid">{visible.map((item, index) => <article className="library-card" key={item.id}><div className="material-card-top"><span>{item.subject}</span>{item.grade && <small>{item.grade}º ano</small>}</div><span className="activity-number">ATIVIDADE {String(index + 1).padStart(2, "0")}</span><h2>{item.title}</h2><p>{item.description}</p><div className="card-footer"><span>Publicado por {item.author.name}</span>{item.fileUrl ? <a className="file-button" href={`${apiUrl}${item.fileUrl}`} target="_blank" rel="noreferrer">Abrir atividade ↗</a> : <span className="reading-material">Leitura disponível</span>}</div></article>)}</div>}</section></main>;
}

function Dashboard({ user, openLogin }: { user: User | null; openLogin: () => void }) {
  if (!canManage(user)) return <main className="dashboard-page"><section className="access-card"><p className="eyebrow">ÁREA RESTRITA</p><h1>Este painel é para administradores.</h1><p>Masters e ADMs podem criar e publicar atividades para os alunos.</p><button className="button button-primary" onClick={openLogin}>Entrar como administrador</button></section></main>;
  return <main className="dashboard-page"><section className="dashboard-header"><p className="eyebrow">PAINEL DO {user!.role === "MASTER" ? "MASTER" : "ADMINISTRADOR"}</p><h1>Gestão de atividades</h1><p>Publique conteúdos, acompanhe as atividades recentes e administre os cadastros sem carregar listas inteiras.</p></section><section className="activity-workspace"><aside><p className="eyebrow">PUBLICAÇÃO</p><h2>Uma boa atividade começa simples.</h2><ul><li>Use um título fácil de reconhecer.</li><li>Informe disciplina e série.</li><li>Envie um arquivo ou publique uma leitura.</li></ul></aside><ActivityForm /></section><Management user={user!} /></main>;
}
function ActivityForm() {
  const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const formElement = e.currentTarget; const form = new FormData(formElement); setLoading(true); setMessage(""); try { let fileUrl: string | null = null; const file = form.get("file"); if (file instanceof File && file.size) { const upload = new FormData(); upload.append("file", file); const r = await fetch(`${apiUrl}/api/materials/upload`, { method: "POST", headers: { Authorization: `Bearer ${token()}` }, body: upload }); const data = await r.json(); if (!r.ok) throw new Error(data.message); fileUrl = data.fileUrl; } const r = await fetch(`${apiUrl}/api/materials`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token()}` }, body: JSON.stringify({ title: form.get("title"), description: form.get("description"), subject: form.get("subject"), grade: Number(form.get("grade")), content: form.get("content") || null, fileUrl, status: "PUBLISHED" }) }); const data = await r.json(); if (!r.ok) throw new Error(data.message); formElement.reset(); setMessage("Atividade publicada e disponível na biblioteca."); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível publicar."); } finally { setLoading(false); } }
  return <form className="activity-form" onSubmit={submit}><label>Título da atividade<input name="title" placeholder="Ex.: Lista de funções do 2º grau" required minLength={3} /></label><div className="form-row"><label>Disciplina<input name="subject" placeholder="Ex.: Matemática" required minLength={2} /></label><label>Série<select name="grade"><option value="1">1º ano</option><option value="2">2º ano</option><option value="3">3º ano</option></select></label></div><label>Descrição<textarea name="description" placeholder="Explique o objetivo da atividade." required minLength={3} /></label><label>Orientações <span>(opcional)</span><textarea name="content" placeholder="Inclua instruções ou observações." /></label><label className="upload-label">Anexar arquivo <span>PDF, DOC ou imagem — até 20 MB</span><input name="file" type="file" /></label><button className="button button-primary" disabled={loading}>{loading ? "Publicando…" : "Publicar atividade"}</button>{message && <p className="form-message">{message}</p>}</form>;
}

function Management({ user }: { user: User }) {
  const [tab, setTab] = useState<"activities" | "students" | "admins">("activities");
  const visibleTab = tab === "admins" && user.role !== "MASTER" ? "students" : tab;
  return <section className="management"><div className="management-tabs"><button className={visibleTab === "activities" ? "active" : ""} onClick={() => setTab("activities")}>Atividades</button><button className={visibleTab === "students" ? "active" : ""} onClick={() => setTab("students")}>Alunos</button>{user.role === "MASTER" && <button className={visibleTab === "admins" ? "active" : ""} onClick={() => setTab("admins")}>Administradores</button>}</div>{visibleTab === "activities" ? <ActivityManager /> : visibleTab === "students" ? <UserManager kind="students" /> : <UserManager kind="admins" />}</section>;
}

function ActivityManager() {
  const [items, setItems] = useState<Material[]>([]); const [message, setMessage] = useState("");
  const load = () => fetch(`${apiUrl}/api/materials?all=true`, { headers: { Authorization: `Bearer ${token()}` } }).then(r => r.ok ? r.json() : Promise.reject()).then(setItems).catch(() => setMessage("Não foi possível carregar as atividades."));
  useEffect(() => { load(); }, []);
  async function remove(id: number) { if (!window.confirm("Excluir esta atividade? Esta ação não pode ser desfeita.")) return; const r = await fetch(`${apiUrl}/api/materials/${id}`, { method: "DELETE", headers: { Authorization: `Bearer ${token()}` } }); if (r.ok) load(); else setMessage("Não foi possível excluir esta atividade. Você só pode remover atividades permitidas para seu perfil."); }
  return <div className="manager-panel"><div className="manager-heading"><div><p className="eyebrow">ATIVIDADES RECENTES</p><h2>Publicações</h2></div><span>{items.length} carregadas</span></div>{message && <p className="form-message">{message}</p>}<div className="manager-list">{items.slice(0, 20).map(item => <article key={item.id}><div><strong>{item.title}</strong><span>{item.subject}{item.grade ? ` · ${item.grade}º ano` : ""}</span></div><button className="danger-button" onClick={() => remove(item.id)}>Excluir</button></article>)}{!items.length && !message && <p>Nenhuma atividade encontrada.</p>}</div></div>;
}

type ManagedUser = { id: number; name: string; email: string; role: Role };
type UserPage = { items: ManagedUser[]; page: number; total: number; totalPages: number };
function UserManager({ kind }: { kind: "students" | "admins" }) {
  const [data, setData] = useState<UserPage | null>(null); const [page, setPage] = useState(1); const [message, setMessage] = useState(""); const isAdmin = kind === "admins";
  const endpoint = isAdmin ? "users" : "students";
  const load = () => fetch(`${apiUrl}/api/${endpoint}?page=${page}&limit=12`, { headers: { Authorization: `Bearer ${token()}` } }).then(async r => { if (!r.ok) throw new Error((await r.json()).message); return r.json() as Promise<UserPage>; }).then(setData).catch((e: Error) => setMessage(e.message));
  useEffect(() => { load(); }, [kind, page]);
  async function remove(id: number) { if (!window.confirm("Remover este cadastro?")) return; const r = await fetch(`${apiUrl}/api/${endpoint}/${id}`, { method: "DELETE", headers: { Authorization: `Bearer ${token()}` } }); if (r.ok) load(); else setMessage("Não foi possível remover este cadastro."); }
  return <div className="manager-panel"><div className="manager-heading"><div><p className="eyebrow">{isAdmin ? "EQUIPE" : "CADASTROS"}</p><h2>{isAdmin ? "Administradores" : "Alunos"}</h2></div>{data && <span>{data.total} no total</span>}</div>{isAdmin && <CreateAdmin onCreated={load} />}{message && <p className="form-message">{message}</p>}<div className="manager-list">{data?.items.map(item => <article key={item.id}><div><strong>{item.name}</strong><span>{item.email}</span></div><button className="danger-button" onClick={() => remove(item.id)}>Remover</button></article>)}</div>{data && <div className="pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>← Anterior</button><span>Página {data.page} de {data.totalPages}</span><button disabled={page >= data.totalPages} onClick={() => setPage(page + 1)}>Próxima →</button></div>}</div>;
}

function CreateAdmin({ onCreated }: { onCreated: () => void }) { const [message, setMessage] = useState(""); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); const r = await fetch(`${apiUrl}/api/users`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token()}` }, body: JSON.stringify({ name: form.get("name"), email: form.get("email"), password: form.get("password") }) }); const data = await r.json(); if (!r.ok) return setMessage(data.message ?? "Não foi possível criar o administrador."); e.currentTarget.reset(); setMessage("Administrador criado."); onCreated(); } return <form className="quick-form" onSubmit={submit}><input name="name" placeholder="Nome do administrador" required minLength={2} /><input name="email" type="email" placeholder="E-mail" required /><input name="password" type="password" placeholder="Senha inicial (mín. 8)" minLength={8} required /><button className="button button-primary">Criar ADM</button>{message && <span>{message}</span>}</form>; }

function StudentRegistration() { const [message, setMessage] = useState(""); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); const r = await fetch(`${apiUrl}/api/auth/register`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), email: form.get("email"), password: form.get("password") }) }); const data = await r.json(); if (!r.ok) return setMessage(data.message ?? "Não foi possível criar sua conta."); localStorage.setItem("neuroflux_token", data.token); localStorage.setItem("neuroflux_user", JSON.stringify(data.user)); window.location.assign("/materiais"); } return <main className="registration-page"><section className="registration-card"><p className="eyebrow">CONTA DE ALUNO</p><h1>Comece a estudar.</h1><p>Crie sua conta gratuita para acessar os materiais publicados.</p><form className="activity-form" onSubmit={submit}><label>Nome completo<input name="name" required minLength={2} /></label><label>E-mail<input name="email" type="email" required /></label><label>Senha<input name="password" type="password" minLength={8} required /></label><button className="button button-primary">Criar conta</button></form>{message && <p className="form-message">{message}</p>}</section></main>; }

function Login({ onClose, onLogin }: { onClose: () => void; onLogin: (u: User) => void }) { const [message, setMessage] = useState(""); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); try { const r = await fetch(`${apiUrl}/api/auth/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: f.get("email"), password: f.get("password") }) }); const data = await r.json(); if (!r.ok) throw new Error(data.message); localStorage.setItem("neuroflux_token", data.token); localStorage.setItem("neuroflux_user", JSON.stringify(data.user)); onLogin(data.user); onClose(); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível entrar."); } } return <div className="login-overlay" onMouseDown={onClose}><section className="login-dialog" onMouseDown={e => e.stopPropagation()}><button className="close-login" onClick={onClose}>×</button><p className="eyebrow">ÁREA RESTRITA</p><h2>Entrar na Neuroflux</h2><form onSubmit={submit}><label>E-mail<input name="email" type="email" required /></label><label>Senha<input name="password" type="password" required /></label><button className="button button-primary">Entrar</button></form>{message && <p className="login-message">{message}</p>}</section></div>; }
function ApiError() { return <div className="api-error"><div><p className="eyebrow">ERRO DE SERVIÇO</p><h2>Erro 500</h2><p>Não foi possível conectar ao servidor.</p></div></div>; }
